.PHONY: setup
setup:
	sudo docker-compose up

.PHONY: down
down:
	sudo docker-compose down
	sudo docker container prune

.PHONY: push
push:
	git status
	git add .
	git commit -m "Generated by Makefile"
	git push origin main